name: meditasi_app
description: 'A new Flutter project.'
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  image_picker: ^0.8.6+4 # Versi lebih baru dari 1.1.2
  flutter_svg: ^2.0.10+1
  waterfall_flow: ^3.0.3
  webview_flutter: ^4.9.0
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  firebase_messaging: ^14.9.4
  flutter_local_notifications: ^17.2.3
  cloud_firestore: ^4.17.5
  video_player: ^2.5.4
  camera: ^0.11.0+2
  speech_to_text: ^6.0.0
  audioplayers: ^5.2.1
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  # cupertino_icons: ^1.0.2

  geolocator: ^9.0.1
  google_maps_flutter: ^2.10.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - asset/app_icon/app_icon.png
    - asset/images/types/
    - asset/images/home_cards/
    - asset/images/backgrounds/
    - asset/images/sleep_music/
    - asset/images/meditation_cards/
    - asset/images/icons/
    - asset/images/sleep/
    - asset/images/image_picker/
    - asset/fonts/Roboto/
    - asset/fonts/Poppins/
    - asset/audio/

  fonts:
    - family: Roboto
      fonts:
        - asset: asset/fonts/Roboto/Roboto-Light.ttf
        - asset: asset/fonts/Roboto/Roboto-Regular.ttf
        - asset: asset/fonts/Roboto/Roboto-Medium.ttf
        - asset: asset/fonts/Roboto/Roboto-Bold.ttf

    - family: Poppins
      fonts:
        - asset: asset/fonts/Poppins/Poppins-Light.ttf
        - asset: asset/fonts/Poppins/Poppins-Regular.ttf
        - asset: asset/fonts/Poppins/Poppins-Medium.ttf
        - asset: asset/fonts/Poppins/Poppins-Bold.ttf
