// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaRl3Zp9KNw-daU3hDn3jaHjzXgNNOCJ0',
    appId: '1:478472262860:web:4f5cdeb296af18fcd65e69',
    messagingSenderId: '478472262860',
    projectId: 'codelab3-3a810',
    authDomain: 'codelab3-3a810.firebaseapp.com',
    storageBucket: 'codelab3-3a810.appspot.com',
    measurementId: 'G-ZN1TVNPLGB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrANMnQB2s_GMMzBvsqkjfBx5bLqgPLc8',
    appId: '1:478472262860:android:35d64aa486632ebcd65e69',
    messagingSenderId: '478472262860',
    projectId: 'codelab3-3a810',
    storageBucket: 'codelab3-3a810.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJaq0QSmO4d0rF64pgs-STgntlb7nxvL8',
    appId: '1:478472262860:ios:7156676ee4db8f7ad65e69',
    messagingSenderId: '478472262860',
    projectId: 'codelab3-3a810',
    storageBucket: 'codelab3-3a810.appspot.com',
    iosBundleId: 'com.example.meditasiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJaq0QSmO4d0rF64pgs-STgntlb7nxvL8',
    appId: '1:478472262860:ios:7156676ee4db8f7ad65e69',
    messagingSenderId: '478472262860',
    projectId: 'codelab3-3a810',
    storageBucket: 'codelab3-3a810.appspot.com',
    iosBundleId: 'com.example.meditasiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaRl3Zp9KNw-daU3hDn3jaHjzXgNNOCJ0',
    appId: '1:478472262860:web:0652aba3bc254f13d65e69',
    messagingSenderId: '478472262860',
    projectId: 'codelab3-3a810',
    authDomain: 'codelab3-3a810.firebaseapp.com',
    storageBucket: 'codelab3-3a810.appspot.com',
    measurementId: 'G-NCTEX9FFGT',
  );

}